### ISSUE TITLE
Being logged out when sending mass email

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/source-code#319]
Nick and Alex are finding that the app logs them out every time they try to send a mass email.

Their emails still send but they are redirected to the login page as soon as they hit send.

**Comment by Adam-JF** [comment]
The fix from issue #212 works for a bit, however, the issue pops up again from time to time.

Will require more testing from the team - might be something to look into at the end of the sprint.

**Comment by Adam-JF** [comment]
Consultants are still being logged out when sending 'mass emails' - this constitutes approximately 5 emails or more being sent - (note: even when it does log you out the emails still send)

Below that figure and everything works fine - any idea why this redirect is happening?

**Comment by SimonLab** [comment]
@Adam-JF Can you please confirm that finishing the Bullhorn substitution work is a higher priority than this for this week?

**Comment by Adam-JF** [comment]
@SimonLab The Bullhorn work is still the priority, but this is something that needs to be fixed asap once that work is completed.

**Comment by SimonLab** [comment]
We might need to extract the [gmail authentication](https://github.com/FAC-GM/app/blob/76990076485c740578f4e2be4c41228dab686b51/lib/helpers/sendemail_gmail.js#L28) outside of the send email helper to avoid doing this process for each email sent.

**Comment by SimonLab** [comment]
error from gmail:
```
{ [Error: Backend Error]
code: 500,
errors: 
[ { domain: 'global',
reason: 'backendError',
 message: 'Backend Error' } ] }
```

**Comment by SimonLab** [comment]
error at:
```
 at OAuth2Client._postRequest (/app/node_modules/google-auth-library/lib/auth/oauth2client.js:381:3)
 at postRequestCb (/app/node_modules/google-auth-library/lib/auth/oauth2client.js:343:10)
 at Request._callback (/app/node_modules/google-auth-library/lib/transporters.js:103:7)
at Request.self.callback (/app/node_modules/google-auth-library/node_modules/request/request.js:198:22
```

**Comment by SimonLab** [comment]
The email functionality has been improved with #412

**Comment by Adam-JF** [comment]
Fixed, working great.

**Comment by Adam-JF** [comment]
The issue has popped up again, Nick and Henry are having this issue regularly.

**Comment by iteles** [comment]
@Adam-JF Have they identified any pattern as to when this happens? Volume of emails? Time of day? Number of emails in a row?
