### ISSUE TITLE
U

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/source-code#417]
![unnamed](https://cloud.githubusercontent.com/assets/15364186/14675189/aea7a2e6-06ff-11e6-9ffb-529bf5923164.png
![amsterdam](https://cloud.githubusercontent.com/assets/15364186/14675256/072f4e28-0700-11e6-982c-498bda61ce50.jpg
![156823562](https://cloud.githubusercontent.com/assets/15364186/14675317/57b09604-0700-11e6-9521-f0c140b97b94.jpg
![214](https://cloud.githubusercontent.com/assets/15364186/14676226/7acc58ea-0704-11e6-9d37-0424dc58c737.jpg)
)
)
)

**Comment by SimonLab** [comment]
@Adam-JF I think the link is broken, what is the U means for?

**Comment by Adam-JF** [comment]
Sorry, this is for personal reference relating to a job posting - i'm just using Github to store my image URLs.
