### ISSUE TITLE
App Gradients

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/source-code#472]
@iteles @SimonLab @heron2014

How difficult is it to change the default background gradient for the entire app?

**Comment by iteles** [comment]
Do you just want to change the colour of the background or have a colour gradient throughout the background?

I would suggest we tread lightly in this area as it's very easy to turn an application into a 90s powerpoint slide with background gradients.

**Comment by Adam-JF** [comment]
I mean to change the background colour for every screen to something a bit more lively.

I'm not proposing anything too mad. Something tasteful, which I'll decide on and have approved. Just wanted to know how long it would take to do across the whole app.

Since it's likely we'll be rocking the purple theme in the future - these are some examples.

![screen shot 2016-06-02 at 15 40 26](https://cloud.githubusercontent.com/assets/15364186/15749044/e4f6fb8a-28d8-11e6-845b-5169a15e7895.png)

![screen shot 2016-06-02 at 15 43 43](https://cloud.githubusercontent.com/assets/15364186/15749048/e94d1214-28d8-11e6-8c03-c41a9af5a78a.png)

**Comment by heron2014** [comment]
@Adam-JF is this issue still relevant after new design?
