### ISSUE TITLE
Client Dashboard - Testing Feedback

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/source-code#491]
Candidates can be progressed through stages as expected - dashboard updates in real time.

Job Title links to custom interview stage creation area as expected.

Stages can be added and removed as expected.

Clicking Account Manager image links to new email creation.

Can we change the font across the client side to Myriad Pro Regular (is this a pain?) http://fontsup.com/family/myriad+pro.html

LI links on Candidate Profiles redirects to LI page as expected - (can we replace LI initials with LI fontawesome icon?)

Cross in top corner removes candidates from dashboard as expected.

Editing job title from clients page is reflected on the dashboard as expected.

Making a role inactive removes it from the dashboard as expected.

Re-activating a job returns it to the dashboard as expected.

Are we going to have a heading image? Not necessarily a gif or anything too loading intensive, but just a still image that you guys would put up on the back end for now, similar to the old '90s powerpoint design' - account manager (Nick) should be larger, as should the client logo - can give you a precise layout if the picture heading is possible.

When on dashboard page ID says it's still the 'client login page', can this be changed to say 'Dashboard'

![screen shot 2016-06-13 at 11 45 09](https://cloud.githubusercontent.com/assets/15364186/16004914/608083bc-315c-11e6-99bf-d4139251a89f.png)

I understand that the blue, underlined text indicates clicking it will link to something, but it's a bit unsightly - can we change this so that it is in bold, not underlined and is font colour #333 

Can we remove the white outlined boxes and replace it with simple grey dividing lines between stages.

**Comment by iteles** [comment]
@Adam-JF 
For this iteration, can I ask that you provide us with a single background image for the header that we can hard-code in across all clients for now so we can try it out and discuss it with Nick tomorrow in the demo? 
As per your original designs, this will be for desktop only and not mobile.

**Comment by SimonLab** [comment]
"account manager (Nick) should be larger, as should the client logo", do you just want the circle icon to be a bit bigger?

**Comment by heron2014** [comment]
@Adam-JF just to confirm 'Can we remove the white outlined boxes and replace it with simple grey dividing lines between stages.'. 

Is this regards to the customize-stages by the client or dashboard?

We have changed the look of the stages: 

![stages-lines](https://cloud.githubusercontent.com/assets/8476884/16006663/2b618582-3166-11e6-952b-9f86ac9695db.png)

**Comment by heron2014** [comment]
@Adam-JF  we have changed the look of dashboard just for test:

![dash-stages](https://cloud.githubusercontent.com/assets/8476884/16006789/d7255fec-3166-11e6-8fc0-5651f0bd79d7.png)

Which design you prefer?

**Comment by Adam-JF** [comment]
@heron2014 I've created a new issue with a design, the way you've separated the stages is perfect though.
