### ISSUE TITLE
Dashboard Temp Design 

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/source-code#492]
Visualisation of dashboard changes from issue #491 

![screen shot 2016-06-13 at 13 03 01](https://cloud.githubusercontent.com/assets/15364186/16006870/31b64f48-3167-11e6-827d-42ccd779bee7.png)

For the M logo and the larger Global M logo.

Can we just create an empty box with the same fill colour as the header of the page and just overlay the larger global M logo inside it, would this achieve the effect shown in the mock up?

![m](https://cloud.githubusercontent.com/assets/15364186/16006897/4e1ef586-3167-11e6-8bf9-f2e833aaf921.png)

![global m logo](https://cloud.githubusercontent.com/assets/15364186/16006603/e9ea0c46-3165-11e6-9017-287a031d393f.png)

**Comment by SimonLab** [comment]
On the login page we are using the squirrel logo, don't you want to use this one on the dashboard also to be consistent?

**Comment by Adam-JF** [comment]
Issue is that the squirrel logo looks horrendous if it's too big so we couldn't use it at the top of the screen  hence the global M branding, I understand that this is inconsistent, but I can't think of another image to use in the header which we can keep consistent across all the pages which would actually make sense.

**Comment by Adam-JF** [comment]
Also, I don't want the clients actual logo there anymore, the images vary too much and at that size most are borderline unrecognisable, similarly they have varying background colours etc. which doesn't help the overall look.

Can we keep the M logo consistent across all client screens in the top left.

**Comment by Adam-JF** [comment]
Hey guys just seen the update to the dashboard, it's looking good.

If we can just add a horizontal line between each of the job roles as above that would be great - similarly what were your thoughts about #489 - below is a screenshot of your update to the dashboard at 75% zoom. This would give people who have 6 stages or fewer a full view of their dashboard without any need for scrolling etc.

![screen shot 2016-06-13 at 13 59 05](https://cloud.githubusercontent.com/assets/15364186/16008279/2c9ade0e-316f-11e6-9feb-3db610f2dcd0.png)

Thoughts?

**Comment by heron2014** [comment]
@Adam-JF in regards to make dashboard in 75% zoom view, I would hold this thought for now and first test it with your clients. (it might happen that for some client-users the candidates and text might be too small). 

@iteles what do you think?

**Comment by heron2014** [comment]
@Adam-JF we have deployed the last changes. Is there anything more that you want to improve?

**Comment by Adam-JF** [comment]
@heron2014 

I still feel like a 75% reduction for the job vacancy view is the best way of showing a dashboard overview. 
The spacing for the {M} logo is a tad off in the header, can we make it closer to the middle of the header?

![screen shot 2016-06-13 at 14 54 42](https://cloud.githubusercontent.com/assets/15364186/16009943/c9c4f6cc-3176-11e6-865e-e403668671f1.png)

Other than that, I think now is a good time to send it over to Nick for his feedback.

I believe I may have come up with a solution regarding how we displays dashboards across the entire app and will be posting these soon for you to look at. For this sprint though I'd say it's looking good.

**Comment by SimonLab** [comment]
@Adam-JF refactoring all the css at this stage to reduce all the elements size is not easy and will take some time. It might also add some bugs and can induce a high risk to break the current display of the application. We think at this stage it is better to keep the current version of the application.

However I agree that we need to have more thought on how we can display more information on the page without having to scroll.

**Comment by Adam-JF** [comment]
@SimonLab Now I understand. Fair enough, looks good for now. I can always show it on my computer with both views so Nick and Alex have an idea of it. Great work guys.
