### ISSUE TITLE
Transfer Domain Name - herokuapp to SquirrelHR

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/source-code#494]
We purchased the domain SquirrelHR.co among other variants a few months ago - how difficult would it be to transfer the app over to this domain name?

**Comment by nelsonic** [comment]
@Adam-JF not difficult at all. when do you need it done? (*is it a priority for today / this week...?*)

**Comment by Adam-JF** [comment]
If it could be done today that would be great!

What information will you be needing from us?

**Comment by Adam-JF** [comment]
Would it be possible to action this today/this evening before the demo tomorrow?

**Comment by heron2014** [comment]
I think would need your account details to goDaddy.

**Comment by Adam-JF** [comment]
I'll send you over the details in an email now.
