### ISSUE TITLE
Squirrel Logo

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/source-code#516]
![squirrel logo](https://cloud.githubusercontent.com/assets/15364186/16302874/60277fd8-3945-11e6-8b47-6ed0fbadf474.png)

![screen shot 2016-06-23 at 12 14 00](https://cloud.githubusercontent.com/assets/15364186/16302741/bc511356-3944-11e6-8a92-a524af0bd790.png)

**Comment by iteles** [comment]
That one on the bottom left looks like it survived a car accident!

**Comment by Adam-JF** [comment]
@iteles Awkward... that ones my favourite 😬 

Think it looks like a little Squirrel ninja 👌  Alex has opted for the middle option for now though... but rest assured, I will find a place for the ninja squirrel somewhere in the app...

**Comment by iteles** [comment]
Hahaha I thought it was a bandage on its head and immediate though 'road kill' 😆 👌

**Comment by Adam-JF** [comment]
![squirrel logo black](https://cloud.githubusercontent.com/assets/15364186/16412922/ad2e31a2-3d26-11e6-88df-3ef4b9ad4685.png)
