### ISSUE TITLE
Upload csv matching

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/source-code#549]
There is a big problem with the csv uploads pairing with existing profiles.

There are now thousands of instances where an upload has created a duplicate profile in spite of the names and email addresses of those who have been uploaded being identical to those already in the app.

The matching is not working consistently - this is a big problem because if we are uploading Business Development lists, then without the matching profile information we cannot distinguish between who is a client and who is not.

**Comment by iteles** [comment]
Hey Adam, we'll need more information on this to help diagnose the root of the problem - examples of duplicates and the file that caused them please

**Comment by Adam-JF** [comment]
I will send over the files I used for the uploads. The issue became particularly apparent following the upload of three BD lists.

![screen shot 2016-07-12 at 15 02 58](https://cloud.githubusercontent.com/assets/15364186/16769770/f0289daa-4841-11e6-8cbd-8d9adf595761.png)

![screen shot 2016-07-12 at 15 02 26](https://cloud.githubusercontent.com/assets/15364186/16769761/eb3a6828-4841-11e6-8af9-930f7d810c26.png)

Below are examples of duplicates - these are the first three results on BD List A, all are duplicated with the same email address and name of someone who is already in the app. 

![screen shot 2016-07-12 at 15 07 24](https://cloud.githubusercontent.com/assets/15364186/16770023/e6f45eda-4842-11e6-9afe-64a4569d2b3f.png)
![screen shot 2016-07-12 at 15 07 38](https://cloud.githubusercontent.com/assets/15364186/16770025/e9d0b086-4842-11e6-9912-3c3026e6eca3.png)
![screen shot 2016-07-12 at 15 07 05](https://cloud.githubusercontent.com/assets/15364186/16770010/ddcdbfae-4842-11e6-9b15-eea4f62b0620.png)

**Comment by iteles** [comment]
@Adam-JF Thanks for this. 

Having done some investigation, our current hypothesis is that the elastic search setup isnt getting through email lists of that size in time to update the application. Could you please try breaking that list into 500 emails at a time and uploading it in pieces to test this hypothesis?

**Comment by Adam-JF** [comment]
@iteles I tested this hypothesis and sadly, it is not the case.

I used BD Tester as a new list and uploaded a file of 477 people all whom should be in the app, in this instance, 0 matched up with existing profiles and therefore 477 duplicates where created in the app.

![screen shot 2016-07-14 at 09 14 54](https://cloud.githubusercontent.com/assets/15364186/16832742/982a78ae-49a3-11e6-9d37-b9372e4db9fa.png)

![screen shot 2016-07-14 at 09 15 04](https://cloud.githubusercontent.com/assets/15364186/16832744/9c1e24ec-49a3-11e6-93d2-0f15c1c34cca.png)

**Comment by Adam-JF** [comment]
@iteles @heron2014 I feel we need to run the script which removes the duplicated profiles without the LI name on the app.

There are now far too many duplicates and we don't want to cause issues with candidates/clients.

However, before that's done, if someone is removed using the script in the app and they've been emailed, if we then upload a csv later on when everything is working, will it still register an email against their profile?

Is the sent email functionality/ability to see the contents of an email sent, linked to the person's email address or their whole profile?

**Comment by heron2014** [comment]
@Adam-JF if we run the script we will remove all empty profiles (profile which don't have LI url) and all relevant information to that profile will be removed. When you upload the csv list again all profiles will be treated as brand new one. If happened that the email has been sent to one of these removed profiles - the link to the sent email will be gone.

**Comment by heron2014** [comment]
@Adam-JF can you please send me over the files that creates the duplicates, thank you

**Comment by Adam-JF** [comment]
@heron2014 Understood, I think we need to run the script regardless to clean up our database before we implement a fix. If you could run that today and let me know that would be great.

I will send over the three files that caused the biggest issues.

**Comment by heron2014** [comment]
@Adam-JF 5404 empty profiles have been deleted. Thanks for the files.

**Comment by heron2014** [comment]
@Adam-JF I have tested the upload list for example Bd Tester with 477 candidates and it uploaded as expected, no duplicates. Could you please test it again.

**Comment by Adam-JF** [comment]
@heron2014 A significant improvement, not quite perfect but certainly a lot better.

The below profile went astray but was the only instance.

![screen shot 2016-07-18 at 13 32 42](https://cloud.githubusercontent.com/assets/15364186/16914857/5c888df8-4cec-11e6-8b95-204971e7af77.png)

**Comment by heron2014** [comment]
@Adam-JF Yes I can see few Bogdan Popa profiles, although they are all unique because of different email address.
![bogdan-popa](https://cloud.githubusercontent.com/assets/8476884/16917638/5643fc94-4cfa-11e6-89ab-8d5a27b68c75.png)

**Comment by heron2014** [comment]
@Adam-JF Please update the status of this issue, based on latest tests. Thank you

**Comment by Adam-JF** [comment]
@heron2014 Working considerably better/no issues recently, will be uploading some big lists during this week so will keep you updated next time I try an 1000+ list.
