### ISSUE TITLE
Searchly Indices

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/source-code#571]
Would one of you mind telling me what is contained in the following indices?

They're stored on Searchly.

globalm
gmcontact_bak
globalmclear
toad 
.kibana

**Comment by nelsonic** [comment]
@SimonLab is the _best_ person to answer this...

**Comment by iteles** [comment]
@nelsonic @Adam-JF I believe the email I sent across answers what you needed in terms of the indices? Let us know if you need more.
